### ISSUE TITLE
Item not showing up properly

### ISSUE THREAD

**Issue by Brentinn** [GuardianOfWynn/builder#1]
![image](https://github.com/GuardianOfWynn/builder/assets/154847991/bb7d0bbd-341f-4ebe-8fca-004f0c06c642)

![image](https://github.com/GuardianOfWynn/builder/assets/154847991/830052fb-f549-4df4-abc1-4b4ab6cc6894)

 
 
 Helmet and chest plate icon's not showing properly

**Comment by victorbetoni** [comment]
Fixed in incoming commit.
Thanks!
