### ISSUE TITLE
positive IDs with min id being 0% show red

### ISSUE THREAD

**Issue by A3pki** [GuardianOfWynn/builder#2]
Positive IDs that have a minimum value of 0 show as red in gsw crafter, example below
https://guardianofwynn.github.io/builder/#/CR-4-EyIzDREyGtDF-2-10-0-33

**Comment by A3pki** [comment]
<img width="414" alt="GsW Crafter png" src="https://github.com/GuardianOfWynn/builder/assets/154861173/bb85b058-db75-4376-b6f5-7595d0fb8516">

**Comment by victorbetoni** [comment]
Fixed in incoming release. Thanks!
