### ISSUE TITLE
Combat lv. min isnt showing the correct value

### ISSUE THREAD

**Issue by Atmisuki** [GuardianOfWynn/builder#3]
Value shown is according to highest level ingredient instead of material level
![4B8468E5-A653-4C26-8727-74A6D90864C8](https://github.com/GuardianOfWynn/builder/assets/154864051/be8abe1a-48d6-485c-ac19-87fdc084d9d2)

**Comment by victorbetoni** [comment]
Fixed in incoming release. Thanks!
