### ISSUE TITLE
couple of nitpicks + link no workie :>

### ISSUE THREAD

**Issue by A3pki** [GuardianOfWynn/builder#4]
- copy recipe gives this link https://guardianofwynn.github.io/builder/#/CR-9-NKNKNKNKNKNK-2-10-0-11 (doesnt work, i think its because its old url lmao)
- https://guardianofwynn.github.io/builder/#/crafter/CR-9-NKNKNKNKNKNK-2-10-0-33 for some reason it says dernic oil in the top left, even though its starfish which it does say in the right
- it would be cool if i could see how much i need of each material like i can in wynncrafter

![image](https://github.com/GuardianOfWynn/builder/assets/154861173/26befa42-5d8d-4c80-8c24-e733833180a7)

:3

**Comment by victorbetoni** [comment]
Hello!
1 - Yes, the URL not working is due to new URL pattern, which includes /crafter/ after the #.
2 - Fixed in incoming release.
3 - Implemented in incoming release.
Thanks!
